version: '3.7'
services:
    db:
      image: postgres:12-alpine
      container_name: postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      volumes:
        - db_data:/var/lib/postgresql/data
      ports:
        - 5432:5432

volumes:
  db_data: